# Generated by Django 4.0.6 on 2023-09-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='asistencia',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='TaGramar',
            field=models.IntegerField(default=0, verbose_name='TaGramar'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='TaPreguntas',
            field=models.IntegerField(default=0, verbose_name='TaPreguntas'),
        ),
    ]
